### ISSUE TITLE
Утверждение использования npm как единственного поддерживаемого пакетного менеджера

### ISSUE THREAD

**Issue by BANOnotIT** [QIWI-API/qiwi-payment-widgets#23]
Нахождение в проекте `yarn.lock` и `package-lock.json` может путать. Может показаться, что использование `yarn` будет работать так же, как и npm, но это не так.

Кажется, что есть смысл в удалении `yarn.lock` так как он не поддерживается и уже 2 года не обновлялся.

**Comment by Khromushkin** [comment]
#24
